const TYPE_ACTION = {
    TODO: {
        GET: 'GET_TODO',
        GET_SAGA: 'GET_TODO_SAGA',
        POST: 'POST_TODO',
        POST_SAGA: 'POST_TODO_SAGA',
        UPDATE: 'UPDATE_TODO',
        UPDATE_SAGA: 'UPDATE_TODO_SAGA',
        DELETE: 'DELETE_TODO',
        DELETE_SAGA: 'DELETE_TODO_SAGA',
        COMPLETE_TODO: 'COMPLETE_TODO',
        COMPLETE_TODO_SAGA: 'COMPLETE_TODO_SAGA',
        UNCOMPLETED_ALL: 'UNCOMPLETED_ALL',
        UNCOMPLETED_ALL_SAGA: 'UNCOMPLETED_ALL_SAGA',
        TURN_COMPLETED_ALL: 'TURN_COMPLETED_ALL',
        TURN_COMPLETED_ALL_SAGA: 'TURN_COMPLETED_ALL_SAGA',
        DELETE_ALL_TODO_COMPLETED: 'DELETE_ALL_TODO_COMPLETED',
        DELETE_ALL_TODO_COMPLETED_SAGA: 'DELETE_ALL_TODO_COMPLETED_SAGA',

    }
}
export default TYPE_ACTION;