const TYPE_ACTION = {
    TODO: {
        GET: 'GET_TODO',
        POST: 'POST_TODO',
        UPDATE: 'UPDATE_TODO',
        DELETE: 'DELETE_TODO',
        COMPLETE_TODO: 'COMPLETE_TODO',
        UNCOMPLETED_ALL: 'UNCOMPLETED_ALL',
        TURN_COMPLETED_ALL: 'TURN_COMPLETED_ALL',
        DELETE_ALL_TODO_COMPLETED: 'DELETE_ALL_TODO_COMPLETED',

    }
}
export default TYPE_ACTION;
